script: "if [ $PERFORMANCE_SPECS ];then bundle exec rake performance_specs --trace; else bundle exec rake --trace; fi"

rvm:
  - "1.9.3"
  - "2.0.0"
  - "jruby"
  - "rbx-2"

env:
 - "RAILS_VERSION=rails3"
 - "RAILS_VERSION=rails4"
 - "RAILS_VERSION=pojs"

matrix:
  include:
    - rvm: "2.0.0"
      env: "PERFORMANCE_SPECS=true"
  exclude:
    - rvm: "rbx"
      env: "RAILS_VERSION=pojs"
    - rvm: "jruby"
      env: "RAILS_VERSION=pojs"
